src/Serilog.Expressions/Templates/Ast/FormattedExpression.cs
src/Serilog.Expressions/Templates/Compilation/CompiledFormattedExpression.cs
src/Serilog.Expressions/Templates/Compilation/TemplateCompiler.cs
src/Serilog.Expressions/Templates/Parsing/TemplateParser.cs
src/Serilog.Expressions/Templates/Rendering/LevelRenderer.cs
src/Serilog.Expressions/Templates/Rendering/Padding.cs
test/Serilog.Expressions.Tests/Cases/template-evaluation-cases.asv
test/Serilog.Expressions.Tests/TemplateParserTests.cs

Based on serilog/serilog, so should behave very similarly to message templates/output templates.

Implement alignment specifiers in templates, fixes #7

---

README.md
src/Serilog.Expressions/Expressions/BuiltInProperty.cs
src/Serilog.Expressions/Expressions/Compilation/Linq/EventIdHash.cs
src/Serilog.Expressions/Expressions/Compilation/Linq/Intrinsics.cs
src/Serilog.Expressions/Expressions/Compilation/Linq/LinqExpressionCompiler.cs
src/Serilog.Expressions/Expressions/Compilation/Wildcards/WildcardComprehensionTransformer.cs
src/Serilog.Expressions/Expressions/Operators.cs
src/Serilog.Expressions/Expressions/Runtime/RuntimeOperators.cs
src/Serilog.Expressions/Serilog.Expressions.csproj
test/Serilog.Expressions.Tests/Cases/expression-evaluation-cases.asv
test/Serilog.Expressions.Tests/FormatParityTests.cs
test/Serilog.Expressions.Tests/Serilog.Expressions.Tests.csproj

I'm frequently pointing people to this library as a means to customize JSON output, with `CompactJsonFormatter`, `RenderedCompactJsonFormatter`, or `JsonFormatter` as the starting point.
This PR adds a test that attempts to replicate these formats byte-for-byte, so that we can identify gaps and inconsistencies.
Along the way:
* Added `@i` and `@r` properties that mirror the [CLEF built-ins with those names](https://github.com/serilog/serilog-formatting-compact#reified-properties) 
* Added `UtcDateTime(d)`, `Now()`, `ToString(x, f)` (fixes #18)
* Fixed wildcard comprehensions with unary conditions - `IsDefined(@p[?])` now works as expected (any property is defined :-))
* Spotted some instances of #19 and added comments
* Re-targeted tests to `net5.0`
* Bumped version to 1.1

Test templates by comparing output with existing formatters

---

src/Serilog.Expressions/Expressions/Ast/Expression.cs
src/Serilog.Expressions/Expressions/Ast/IndexOfMatchExpression.cs
src/Serilog.Expressions/Expressions/Compilation/ExpressionCompiler.cs
src/Serilog.Expressions/Expressions/Compilation/Text/LikeSyntaxTransformer.cs
src/Serilog.Expressions/Expressions/Compilation/Wildcards/WildcardComprehensionTransformer.cs
src/Serilog.Expressions/Expressions/Compilation/Wildcards/WildcardSearch.cs
src/Serilog.Expressions/Expressions/Parsing/ExpressionParser.cs
src/Serilog.Expressions/Expressions/SerilogExpression.cs
test/Serilog.Expressions.Tests/Cases/expression-evaluation-cases.asv
test/Serilog.Expressions.Tests/Cases/translation-cases.asv
test/Serilog.Expressions.Tests/ExpressionEvaluationTests.cs
test/Serilog.Expressions.Tests/ExpressionTranslationTests.cs
test/Serilog.Expressions.Tests/Support/AsvCases.cs
test/Serilog.Expressions.Tests/TemplateEvaluationTests.cs

_Serilog.Expressions_ has a number of language features in common with Seq (though the implementations are generally very different). I checked over how wildcards are evaluated after having a [bug reported in Seq's implementation](https://github.com/datalust/seq-tickets/issues/1150), to see whether similar issues existed over here.
And, yes! - Found some problems in how wildcards work, leading to potentially incorrect results in the presence of indexing into potentially-undefined values.
After adding some new test cases for that issue, I fleshed out testing of `like` and found that expressions aren't being correctly anchored, here - `A like 'a%'` should anchor `a` at the beginning of the target string, but doesn't, and end anchoring was similarly broken.
This PR fixes both sets of issues.

Fix wildcard semantics; fix like clause anchoring

---

src/Serilog.Expressions/Expressions/Operators.cs
test/Serilog.Expressions.Tests/Cases/translation-cases.asv

Missed one vital detail, leading to multi-wildcard paths not being transformed correctly.

Additional wildcard comprehension test case and fix

---

README.md
example/Sample/Program.cs
src/Serilog.Expressions/Expressions/Compilation/Linq/LinqExpressionCompiler.cs
src/Serilog.Expressions/Expressions/Compilation/OrderedNameResolver.cs
src/Serilog.Expressions/Expressions/Compilation/Text/LikeSyntaxTransformer.cs
src/Serilog.Expressions/Expressions/Compilation/Text/TextMatchingTransformer.cs
src/Serilog.Expressions/Expressions/Compilation/Transformations/IdentityTransformer.cs
src/Serilog.Expressions/Expressions/Compilation/Transformations/SerilogExpressionTransformer.cs
src/Serilog.Expressions/Expressions/Compilation/Variadics/VariadicCallRewriter.cs
src/Serilog.Expressions/Expressions/Compilation/Wildcards/WildcardSearch.cs
src/Serilog.Expressions/Expressions/NameResolver.cs
src/Serilog.Expressions/Serilog.Expressions.csproj
src/Serilog.Expressions/Templates/Compilation/TemplateFunctionNameResolver.cs
src/Serilog.Expressions/Templates/Compilation/UnreferencedProperties/ExpressionReferencedPropertiesFinder.cs
src/Serilog.Expressions/Templates/Compilation/UnreferencedProperties/TemplateReferencedPropertiesFinder.cs
src/Serilog.Expressions/Templates/Compilation/UnreferencedProperties/UnreferencedPropertiesFunction.cs
src/Serilog.Expressions/Templates/ExpressionTemplate.cs
test/Serilog.Expressions.Tests/Expressions/NameResolverTests.cs
test/Serilog.Expressions.Tests/Templates/UnreferencedPropertiesFunctionTests.cs

* Allow all functions to accept a `LogEvent` parameter
* Adds virtual `NameResolver.TryBindFunctionParameter()` to support user-defined  function parameter types
* Combine these to implement a `Rest()` function, usable in templates only, that matches the behavior of `{Properties}` in Serilog output templates (i.e. all properties not referenced elsewhere in the template or message)
* Bump version to 3.1.0 (added feature)
With this one I think we're _finally_ feature-complete.

Improve parameter binding and allow user-defined parameter types

---

README.md
src/Serilog.Expressions/Expressions/Compilation/Variadics/VariadicCallRewriter.cs
src/Serilog.Expressions/Expressions/Operators.cs
src/Serilog.Expressions/Expressions/Runtime/RuntimeOperators.cs
test/Serilog.Expressions.Tests/Cases/expression-evaluation-cases.asv

Useful when constructing JSON values. A simple implementation requiring that all arguments are defined, non-null strings, and using `string.operator+()` under the hood.

`Concat(s0, s1, ..sN)`

---

README.md
src/Serilog.Expressions/Expressions/Compilation/Linq/LinqExpressionCompiler.cs
src/Serilog.Expressions/Expressions/Compilation/Variadics/VariadicCallRewriter.cs
src/Serilog.Expressions/Expressions/Runtime/RuntimeOperators.cs
src/Serilog.Expressions/Templates/Compilation/UnreferencedProperties/UnreferencedPropertiesFunction.cs
test/Serilog.Expressions.Tests/Cases/template-evaluation-cases.asv
test/Serilog.Expressions.Tests/ExpressionCompilerTests.cs
test/Serilog.Expressions.Tests/Templates/UnreferencedPropertiesFunctionTests.cs

This is not always desirable behavior, and since it has a perf cost, it might as well be the opt-in:
| Function | Description |
| :--- | :--- |
| `Rest([deep])` | In an `ExpressionTemplate`, returns an object containing the first-class event properties not otherwise referenced in the template. If `deep` is `true`, also excludes properties referenced in the event's message template. |
`LinqExpressionCompiler` now uses method argument names and default values when binding function calls, so user-defined functions can have optional arguments, and we don't have to add custom rewrite rules for every function with optional args.

Default `rest()` to ignore message templates by default

---

README.md

I tried the example code from the readme and could not get it to work as it does not expect an array for nameResolver

Update Readme: Fix up example for custom NameResolver

---

README.md
appveyor.yml
src/Serilog.Expressions/Expressions/Compilation/Arrays/ConstantArrayEvaluator.cs
src/Serilog.Expressions/Expressions/Compilation/ExpressionCompiler.cs
src/Serilog.Expressions/Expressions/Compilation/Linq/LinqExpressionCompiler.cs
src/Serilog.Expressions/Expressions/Compilation/OrderedNameResolver.cs
src/Serilog.Expressions/Expressions/Compilation/Wildcards/WildcardComprehensionTransformer.cs
src/Serilog.Expressions/Expressions/NameResolver.cs
src/Serilog.Expressions/Serilog.Expressions.csproj
test/Serilog.Expressions.Tests/Expressions/NameResolverTests.cs

* #62 - README update, fix custom name resolver example (@warrenbuckley)
* #67 - support aliasing of built in property names, to ease migration from _Serilog.Filters.Expressions_ (@nblumhardt)

3.3.0 Release

---

src/Serilog.Expressions/Expressions/Runtime/RuntimeOperators.cs
test/Serilog.Expressions.Tests/Cases/template-evaluation-cases.asv

Fixes #69 
This makes the format specifiers accepted for levels consistent between the template syntax `{@l:u3}` and function-call syntax `{ToString(@l, 'u3')}`.

Add support for for formatting short level names via `ToString()`

---

Build.ps1
appveyor.yml
src/Serilog.Expressions/Expressions/Runtime/RuntimeOperators.cs
test/Serilog.Expressions.Tests/Cases/expression-evaluation-cases.asv
test/Serilog.Expressions.Tests/ExpressionEvaluationTests.cs
test/Serilog.Expressions.Tests/Serilog.Expressions.Tests.csproj
test/Serilog.Expressions.Tests/Support/TestHelperNameResolver.cs

Resolves #76
Serilog's `DictionaryValue` is a bit unloved; support was initially missed because the original codebase from which Serilog.Expressions is derived targeted the JSON data model only, and non-string-key dictionaries aren't a thing there.

Enable wildcard indexers over dictionary elements

---

README.md

It took me quite a while to figure out how to conditionally check if the `rest(true)` object was empty, so here it is:

Add a recipie for checking if an object is empty

---

src/Serilog.Expressions/Templates/Compilation/NameResolution/TemplateLocalNameBinder.cs
test/Serilog.Expressions.Tests/Cases/template-evaluation-cases.asv

Fix a bug whereby names bound in repetition expressions can't be used in the enumerable argument to nested repetition expressions. (The test hopefully says it all 😅 .)

Bind template locals appearing in repetition enumerable expressions

---

src/Serilog.Expressions/Templates/Compilation/CompiledRepetition.cs
test/Serilog.Expressions.Tests/Cases/template-evaluation-cases.asv

This is useful when conditionally formatting the first or last element in a list, or when generating unique identifiers for each element - for example, when formatting HTML tables.
```
{#each e, i in ['a', 'b', 'c']}
Element: {e}
Index: {i}
{#end}
```
produces:
```
Element: a
Index: 0
Element: b
Index: 1
Element: c
Index: 2
```

Supply the list element index in the second #each parameter when enumerating

---

src/Serilog.Expressions/Expressions/Compilation/Linq/LinqExpressionCompiler.cs
test/Serilog.Expressions.Tests/Cases/expression-evaluation-cases.asv

This is a bugfix, but needs to be in a new major because it's also a breaking change.
`ElementAt(a, b) ci` plays the role of a case-insensitive accessor.

Accessors such as `a.B` should be case-sensitive

---

example/Sample/Sample.csproj
src/Serilog.Expressions/Expressions/Compilation/Linq/ExpressionConstantMapper.cs
src/Serilog.Expressions/Expressions/Compilation/Linq/Intrinsics.cs
src/Serilog.Expressions/Serilog.Expressions.csproj
src/Serilog.Expressions/Templates/Compilation/TemplateCompiler.cs
src/Serilog.Expressions/Templates/Compilation/TemplateFunctionNameResolver.cs
src/Serilog.Expressions/Templates/Compilation/Unsafe/UnsafeOutputFunction.cs
src/Serilog.Expressions/Templates/Encoding/EncodedCompiledTemplate.cs
src/Serilog.Expressions/Templates/Encoding/EncodedTemplateFactory.cs
src/Serilog.Expressions/Templates/Encoding/EscapableEncodedCompiledFormattedExpression.cs
src/Serilog.Expressions/Templates/Encoding/PreEncodedValue.cs
src/Serilog.Expressions/Templates/Encoding/TemplateOutputEncoder.cs
src/Serilog.Expressions/Templates/ExpressionTemplate.cs
src/Serilog.Expressions/Templates/Themes/ThemedJsonValueFormatter.cs
test/Serilog.Expressions.PerformanceTests/ComparisonBenchmark.cs
test/Serilog.Expressions.PerformanceTests/Serilog.Expressions.PerformanceTests.csproj
test/Serilog.Expressions.PerformanceTests/Support/Some.cs
test/Serilog.Expressions.Tests/Cases/template-encoding-cases.asv
test/Serilog.Expressions.Tests/Serilog.Expressions.Tests.csproj
test/Serilog.Expressions.Tests/Support/ParenthesizingEncoder.cs
test/Serilog.Expressions.Tests/Support/Some.cs
test/Serilog.Expressions.Tests/Support/StringHashPrefixingTheme.cs
test/Serilog.Expressions.Tests/TemplateEncodingTests.cs
test/Serilog.Expressions.Tests/TemplateParserTests.cs

For `ExpressionTemplate` to be useful in scenarios like HTML email, webhook URL, or URL-encoded `POST` body construction, a safer mechanism is needed for output encoding.
For example, imagine we rewrite _Serilog.Sinks.Email_ to use `ExpressionTemplate`, a message body might look like:
```html
<p class="error">Exception: {@x}</p>
```
Since the email is being fed exceptions from a running application, a malicious user might cause an error to be generated with HTML in the message:
```
System.InvalidOperationException: <a href="my-bad-site">Click to see more info</a><br><br><br>is not a valid username.
at ...
```
Today, to defend against this an `htmlencode` user-defined function might be used:
```html
<p class="exception">Exception: {htmlencode(@x)}</p>
```
But, we all know how easily opt-in …

Output encoding

---

src/Serilog.Expressions/Expressions/StaticMemberNameResolver.cs

I've found that `Serilog.Expressions` produces nasty startup crash when an app that uses this lib is built with `PublishTrimmed=true`:
```
Unhandled exception. System.ArgumentException: The function name `Substring` was not recognized.
at Serilog.Expressions.Compilation.Linq.LinqExpressionCompiler.Transform(CallExpression)
at Serilog.Expressions.Compilation.Transformations.SerilogExpressionTransformer`1.Transform(Expression expression)
at Serilog.Expressions.Compilation.Linq.LinqExpressionCompiler.Compile(Expression, IFormatProvider , NameResolver)
at Serilog.Expressions.Compilation.ExpressionCompiler.Compile(Expression, IFormatProvider , NameResolver)
at Serilog.Expressions.SerilogExpression.TryCompileImpl(String, IFormatProvider , NameResolver , CompiledExpression& , String& )
at …
```

Fix crash on apps built with PublishTrimmed=True

---

README.md

Copied trace id and span id information from https://github.com/serilog/serilog-formatting-compact to this document

Document TraceId and SpanId properties

---

src/Serilog.Expressions/Serilog.Expressions.csproj

Serilog version 3.1.0 causes stackoverflowException. https://github.com/serilog/serilog/pull/1977

Upgraded Serilog version

---

src/Serilog.Expressions/Serilog.Expressions.csproj
src/Serilog.Expressions/Templates/Compilation/UnreferencedProperties/ExpressionReferencedPropertiesFinder.cs
test/Serilog.Expressions.Tests/Templates/UnreferencedPropertiesFunctionTests.cs

Fixes #107
The existing behavior was intended to allow `@p.X` to be an escape hatch so that the reference to `X` is invisible to `rest()`. This turns out to be confusing in actual use.
The new ways to hide a property reference from `rest()` are:
```
let p = @p in p.X
```
or
```
@p[concat('X', '')]
```
etc.
Major version bump because this is likely to affect a few templates in use.

Make the `rest()` function aware of `@p.X` and `@p['X']` (breaking change)

---

README.md
src/Serilog.Expressions/Expressions/Operators.cs
src/Serilog.Expressions/Expressions/Runtime/RuntimeOperators.cs
test/Serilog.Expressions.Tests/Cases/expression-evaluation-cases.asv
test/Serilog.Expressions.Tests/Expressions/Runtime/RuntimeOperatorsTests.cs
test/Serilog.Expressions.Tests/Support/Some.cs

Add the `Inspect()` function

---

Build.ps1
src/Serilog.Expressions/Expressions/Helpers.cs
src/Serilog.Expressions/Expressions/Runtime/Coerce.cs
src/Serilog.Expressions/Expressions/Runtime/RuntimeOperators.cs
src/Serilog.Expressions/Serilog.Expressions.csproj
test/Serilog.Expressions.Tests/Cases/expression-evaluation-cases.asv
test/Serilog.Expressions.Tests/ExpressionTranslationTests.cs

See https://github.com/serilog/serilog-expressions/pull/111#issuecomment-2162895375

Fix .NET Framework builds

---

src/Serilog.Expressions/Templates/Compilation/CompiledTimestampToken.cs
src/Serilog.Expressions/Templates/Compilation/TemplateCompiler.cs
test/Serilog.Expressions.Tests/Cases/template-evaluation-cases.asv
test/Serilog.Expressions.Tests/Support/Some.cs
test/Serilog.Expressions.Tests/TemplateEvaluationTests.cs

Similar to https://github.com/serilog/serilog/pull/2094
Removed allocations from `DateTimeOffset.ToString` by using `ISpanFormattable.TryFormat` API
```csharp
[MemoryDiagnoser]
[SimpleJob(RuntimeMoniker.Net80)]
[SimpleJob(RuntimeMoniker.Net90)]
public class ExpressionBenchmark
{
private TextWriter nullWriter = TextWriter.Null;
private ExpressionTemplate expressionFormatter = new ExpressionTemplate("[{@t:HH:mm:ss.fff} {@l:u3} ({SourceContext})] {@m}\n");
private readonly LogEvent logEvent = new LogEvent(DateTimeOffset.Now, LogEventLevel.Information, null, new MessageTemplateParser().Parse("Something happens in method {Method} with parameter {Param}, context: {Context}"), new LogEventProperty[
]
{
new LogEventProperty("Method", new ScalarValue("ProcessMessages")),
new …
```

Removed allocations for timestamp
